version: '3'

services:
  database:
    image: postgres:10
    environment:
      POSTGRES_USER: remotodojo
      POSTGRES_PASSWORD: remotodojo
  backend:
    build: .
    image: remotodojo
    command: bash /remotodojo/server/django_devserver.sh
    volumes:
      - .:/remotodojo
    depends_on:
      - database
    ports:
      - 8000:8000
    environment:
      DB_HOST: database
      DB_USER: remotodojo
      DB_PASS: remotodojo
      DJANGO_SETTINGS_MODULE: remotodojo.settings.dev
      DJANGO_SECRET_KEY: django-insecure-2ncga_&6oq3@hxu(@qrj_*ow71d7_=otovlcd_95ga_#^!kr#q
