# Generated by Django 3.2.10 on 2021-12-19 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_content_changed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-content_changed',), 'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
    ]
